name: NightVision
version: '1.0'
main: net.greenwoodmc.nightvision.NightVision
api-version: 1.20
authors: [ VoidemLIVE ]
description: /nv command
website: https://greenwoodmc.net

commands:
  nightvision:
    description: Night vision
    aliases: [nightvision, nv]
    permission: gwnv.use
    default: false